
/* Create Tables */

CREATE TABLE `CUSTOMER`
(
	`CUSTOMERID` INT NOT NULL AUTO_INCREMENT,
	`FIRSTNAME` VARCHAR(50) NULL,
	`LASTNAME` VARCHAR(50) NULL,
	`PESEL` VARCHAR(50) NULL,
	`ACTIVE` TINYINT NOT NULL DEFAULT 0,

	CONSTRAINT `PK_CUSTOMER` PRIMARY KEY (`CUSTOMERID` ASC)
)

;
