
/* Create Tables */

CREATE TABLE `ARTICLE`
(
	`ARTICLEID` INT NOT NULL AUTO_INCREMENT,
	`CONTENT` VARCHAR(50) NULL,
	`CREATED` VARCHAR(50) NULL,
	`CUSTOMERID` INT NOT NULL,

	CONSTRAINT `PK_CUSTOMER` PRIMARY KEY (`ARTICLEID` ASC),
	CONSTRAINT `FK_CUSTOMER_CUSTOMER_ID` FOREIGN KEY (`CUSTOMERID`) REFERENCES `CUSTOMER` (`CUSTOMERID`)
);
